### ISSUE TITLE
1st cell in each row of TypeLayout has unexpected `padding-left: 1rem`

### ISSUE THREAD

**Issue by liunate** [carbon-design-system/ibm-security#1121]
## Bug - 
1st cell in each row of TypeLayout has unexpected `padding-left: 1rem`

### Description
We upgraded from `@carbon/ibm-security` `1.40` to `1.45` and found the 1st cell of each row of `<TypeLayout>` are indented for `padding-left: 1rem;`. Attached screenshot showing this `@carbon/ibm-security` rule is not honored: 

```scss
.security--type-layout__container__cell:first-of-type {
  width: 1%;
  padding-left: 0;
  white-space: nowrap;
}
```
which is overridden by `carbon-component/structured-list` rule for weaker CSS specificity:
```scss
.bx--structured-list .bx--structured-list-row .bx--structured-list-td:first-of-type, .bx--structured-list .bx--structured-list-row .bx--structured-list-th:first-of-type {
  padding-left: 1rem;
}
```
![image](https://user-images.githubusercontent.com/38996291/139201217-fd4e703e-dfb6-4e82-b2be-88623d482b01.png)

#### Expected behavior

There should be `padding-left` in `<TypeLayout>` at 1st cell of each row

#### Actual behavior

`padding-left: 1rem` is applied to the `<TypeLayout>` at 1st cell of each row

### Steps for reproducing
Check https://ibm-security.carbondesignsystem.com/?path=/docs/components-typelayout--default by dev tool

### Affected browsers
Any

### Optional information

**Version -** 
v1.45
