### ISSUE TITLE
SkeletonText - heights are altered, so design is inconsistent with Carbon

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/ibm-security#296]
## Bug - 

**Expected behavior -**

I expect the `SkeletonText` component, which is used in many Carbon components like the `AccordionSkeleton1`, to have the same height as in Carbon's upstream library.

**Actual behavior -**

When we import the `SkeletonText` component, we are altering the height (halving it, for the most part): https://github.com/carbon-design-system/ibm-security/blob/dev/src/components/SkeletonText/_mixins.scss

```scss
@mixin skeleton-text {
  .#{$prefix}--skeleton {
    &__text {
      height: carbon--mini-units($count: 1);
    }

    &__heading {
      height: carbon--mini-units($count: 2);
    }
  }
}
```

This makes our exported `SkeletonText` shorter than Carbon's. You can see this especially when you compare our exported `AccordionSkeleton` (https://ibm-security.carbondesignsystem.com/?path=/story/components-accordion--with-skeleton) with Carbon's `AccordionSkeleton` (http://react.carbondesignsystem.com/?path=/story/accordion--skeleton) -- with the `AccordionSkeleton` in particular, the height difference doesn't match the non-skeleton text variant of the component & also messes with vertical alignment (you can see our `AccordionSkeleton`'s arrow's vertical alignment is off).

It's possible that we need the `SkeletonText` to be short in some specific context, like for the `CardSkeleton` -- but if that is the case, we should find those specific situations and make *local* style overrides to the height, instead of keeping these global `SkeletonText` height changes and applying them to all situations.
