### ISSUE TITLE
Adding a flag to indicate whether to import security `theme`

### ISSUE THREAD

**Issue by fred104** [carbon-design-system/ibm-security#415]
### Details

- **Application / team -** IBM Resilient

We are recently migrating from bootstrap to Carbon. But without completely removing all the bootstrap styles at once, we are having hybrid styles now. Moreover, we are now providing 3 themes to customers, light, dark, very dark. We define our custom scss variables which will be used in carbon components for these 3 themes. 

When we are trying to import component styles, it looks like it will override our predefined scss variables. Trace through the code base, it seems that `globals/theme` will be imported in some components which causes this issue, such as Button, ComboButton.

```scss
// src/components/Button/_mixins.scss
...
@import '../../globals/theme/index'; // line 13
...
```

```scss
// src/components/ComboButton/_mixins.scss
...
@import '../../globals/index'; // line 7
```

I am wondering if there is a way to not to import the theme and it will consume our predefined scss variables.

### Proposal

Maybe adding a new feature flag?

Requires further investigation

**Comment by SimonFinney** [comment]
Thanks @fred104 - for additional context, would you also mind providing an example of the Sass variables that are being pre-defined?

**Comment by fred104** [comment]
Sure. :) I will post part of code here.

```scss
$default-interactive-01: #0062ff;
$default-interactive-02: #3d3d3d;
$default-interactive-03: #0062ff;
$default-interactive-04: #0062ff;
$default-ui-background: #ffffff;
$default-ui-01: #f3f3f3;
$default-ui-02: #ffffff;
$default-ui-03: #dcdcdc;
$default-ui-04: #8c8c8c;
$default-ui-05: #171717;
$default-text-01: #171717;
$default-text-02: #565656;
$default-text-03: #8c8c8c;
$default-text-04: #ffffff;
$default-text-05: #6f6f6f;

body.darkmode {
  --res-interactive-01: #0062ff;
  --res-interactive-02: #6f6f6f;
  --res-interactive-03: #ffffff;
  --res-interactive-04: #408bfc;
  --res-ui-background: #282828;
  --res-ui-01: #3d3d3d;
  --res-ui-02: #565656;
  --res-ui-03: #565656;
  --res-ui-04: #8c8c8c;
  --res-ui-05: #f3f3f3;
  --res-text-01: #f3f3f3;
  --res-text-02: #bebebe;
  --res-text-03: #8c8c8c;
  --res-text-04: #ffffff;
  --res-text-05: #8d8d8d;
}

$interactive-01: var(--res-interactive-01, $default-interactive-01);
$interactive-02: var(--res-interactive-02, $default-interactive-02);
$interactive-03: var(--res-interactive-03, $default-interactive-03);
$interactive-04: var(--res-interactive-04, $default-interactive-04);
$ui-background: var(--res-ui-background, $default-ui-background);
$ui-01: var(--res-ui-01, $default-ui-01);
$ui-02: var(--res-ui-02, $default-ui-02) !global;
$ui-03: var(--res-ui-03, $default-ui-03);
$ui-04: var(--res-ui-04, $default-ui-04);
$ui-05: var(--res-ui-05, $default-ui-05);
$text-01: var(--res-text-01, $default-text-01);
$text-02: var(--res-text-02, $default-text-02);
$text-03: var(--res-text-03, $default-text-03);
$text-04: var(--res-text-04, $default-text-04);
$text-05: var(--res-text-05, $default-text-05);
```
